### ISSUE TITLE
Could you publish binary? Can't compile with new VS or just can not rum it!

### ISSUE THREAD

**Issue by kaunomedis** [tomas-nestorovic/RIDE#74]
At last when I compiled, I received "CAPS library outdated, 5.1 or newer required!"

**Comment by tomas-nestorovic** [comment]
Hi,

binaries are under the [Releases section](https://github.com/tomas-nestorovic/RIDE/releases) (which is not so well visible here at GitHub - one has to switch to the _Code_ tab and search for it in the middle of the page in column on the right).

Each release comes with all libraries - you may therefore want to place the CAPS library into Windows system folder so that you can run the app even from within Visual Studio :-)

Tomas

**Comment by kaunomedis** [comment]
Thanks, it is working. Still dos not recognized, but I know it is from ZX. On one disk there is visible marking "ST-DOS", other disks first sectors is with text "Simanauskas Darius VILNIUS 1989(C)", "53k CP/M", "D.S. 1989 Vilnius" - looks someone "hacked" strings.

I found disk labeled "system". Converted to binary. Could you check it? It is 5 sector @1K.

[U00_scp.zip](https://github.com/tomas-nestorovic/RIDE/files/10271057/U00_scp.zip)

**Comment by tomas-nestorovic** [comment]
Hi,

well, if the application doesn't recognize the content in an unstructured image (e.g. your *.IMA), it's always up to the user to specify the correct geometry.

I pondered your image. It's 407,552 Bytes long, too short for a double-sided 3.5" 2DD floppy, unlikely to be a single-sided 3.5" 2DD floppy. So I guess it's a double-sided single density 5.25" floppy.

You specified a sector should be 1024 Bytes big - that makes 407552/1024 = 398 sectors on the disk in total. May it be that two sectors are missing on the last track? For then it would be 400 sectors - with expected five sectors per track you specified, it would then make nice 80 tracks in total, aka a double-sided 40 tracks disk.

Such geometry is pre-defined in the _Raw image settings_ dialog:

![image](https://user-images.githubusercontent.com/37716001/208880951-bee64638-292e-4846-a830-b656d0deca8c.png)

![image](https://user-images.githubusercontent.com/37716001/208881306-5fa982a3-64e1-4b5a-ad1c-184bb3d484e6.png)

The question is if the side numbers (0 and 1, in this case) are correct?

I confirmed the settings - the "Cannot recognize the DOS" message appeared, which is expected. The disk was opened, in the _Track Map_ tab I switched to data visualization (Ctrl+2) and immediately saw the root directory with CP/M-based directory entries in it (MS-DOS builds on them as well).

![image](https://user-images.githubusercontent.com/37716001/208881954-69feaee7-2838-41da-b5e1-241530055d95.png)

![image](https://user-images.githubusercontent.com/37716001/208882104-72ad82c6-c47b-4452-a620-80494817afa7.png)

![image](https://user-images.githubusercontent.com/37716001/208882161-95247ccd-4ed7-4b9b-9736-55d01865e319.png)

I tried to find the string "DOS" in the disk content:

![image](https://user-images.githubusercontent.com/37716001/208882698-578e086a-aea5-4fb3-902e-588a18a25417.png)

The first occurrence (I haven't searched further) refers to BDOS which I have no previous experience with :-(

![image](https://user-images.githubusercontent.com/37716001/208882901-73879afa-4b09-40aa-982c-2784ed7453a2.png)

Anyway if you are certain with the geometry (40x2x5 á 1024), then you may continue with dumping the image ([see how](https://nestorovic.hyperlink.cz/ride/html/faq_image2floppy.html)).

Hope it helps somehow.

**Comment by kaunomedis** [comment]
Wow, thank you for your explanation. I need to learn everything you posted. Thanks.
About the size of the disk... it is possible that I lost some of the data during conversion or by disk damage. I am trying to force greaseweazle to understand the format to use multiple reads on bad disks. Many of the disks are very "RED".

![zx0-diskas](https://user-images.githubusercontent.com/87241527/208953640-45637016-4d55-454d-8585-06b78e60742d.png)
This is disk I've send you.

**Comment by kaunomedis** [comment]
Yeap, binary image is not good for testing.
![zx0-diskas2](https://user-images.githubusercontent.com/87241527/208958896-51d4ab80-5495-44b2-b4bc-9a4e69058d25.png)

Here is the flux. If it will allow to attach...
[U00.zip](https://github.com/tomas-nestorovic/RIDE/files/10279610/U00.zip)

**Comment by tomas-nestorovic** [comment]
Hi,

oh man, this looks terribly! 👎

BUT (I've saved, or at least significantly improved, a couple of such disks):

1. _Did you try cleaning the FDD heads?_ I personally use isopropyl alcohol (which evaporates quickly and leaves no traces) that is sold in various stores under various names (e.g. in Hornbach as "Isopropanol"). [Here a video tutorial](https://www.youtube.com/watch?v=m6CEVtOlpoY) for 3.5" drives - a basically the same procedure holds for any other drive.
2. _Did you try cleaning the disk?_ This is a must for any old floppies of unknown origin. I again use isopropyl alcohol, and [this video tutorial](https://www.youtube.com/watch?v=I-MKpgO4nOY) shows virtually exactly how I do it.
3. _Does the disk spin constantly in the drive?_ If you right-click any track and select the _Show track low-level_ command, a track viewer appears. ![image](https://user-images.githubusercontent.com/37716001/209193098-d1e88ae3-b717-42bc-80e9-ba5614801955.png) In it select the _Helpers → Scatter plot_ command. The following is a typical example of a flux deformation due to disk spinning with obstacles in the drive - what should be straight lines is deformed to sort of sinusoids. (Eventually command to see only 99.85 percentile of the data via the _Chart_ menu.) ![image](https://nestorovic.hyperlink.cz/Collection/PcCs/images/Paranoia2fluxy-7806025C.png) If this is the case, simply very gently press the Eject button on the drive while the drive is working with such floppy - you this way release the pressure of both heads on the magnetic disk, making it spin more freely. This requires VERY calm hand :-)
4. _Did you try aligning Head 1 (upper head)?_ I can see an almost systematic error under Head 1 in the Track Map you shared which is often an indicator that the drive needs alignment. Don't worry, it's not a rocket science - the point is that the lower (fixed) and upper (adjustable) heads are [offset by several tracks](https://pbs.twimg.com/media/EZVW_ekUwAMbGgv?format=jpg&name=900x900) (I think eight, but am not sure). The screws of the upper adjustable head must be released and the head positioned so that it [matches with the pressure cap underneath it](https://i.stack.imgur.com/PQEyxm.png). To correctly align the upper head will typically need several iterations of disconnecting the drive, releasing the screws, aligning the head, tightening the screws, and connecting the drive back to see the difference/improvement. [This video](https://www.youtube.com/watch?v=Fkr9Vu6Wiy4) shows what I mean - except the the guy is aligning Head 1 on-the-fly by using a dedicated software to immediately see the difference. I don't have such thing so I always have to stick to the iterative process.

Let me know how you are doing 👍

**Comment by tomas-nestorovic** [comment]
With more than a month of no response, this problem seems to be resolved. If that's not the case, feel free to reopen this issue or create a new one.

**Comment by kaunomedis** [comment]
Sorry, I forgot you and your program. It give me good start and I wrote custom software for my purpose, especially I was in great need for the Disk Monitor images and less for CP/M from ZX clones.
For low level reading, we made great cooperation with Greaseweazle author, as he updated his program with the custom disk format options. Now I can "grind" disk in bad sectors and salvage the data. The problem is not in the bad head alignment or head cleaning, just in the post soviet era many DD disks were written as HD. Some sectors were salvaged after 7 revolutions, 6 retries and 6 seeks! Now I am pushing Greaseweazle to make an option to collect bad sector data for statistical analysis- some sectors have readable data, but bad checksum. Maybe few bytes are lost and rest data in 1024 are good!
